/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 computer.gltf --transform 
Files: computer.gltf [5.18KB] > C:\Users\sksak\Downloads\retro_computer\computer-transformed.glb [123.01KB] (-2275%)
Author: dogflesh (https://sketchfab.com/dogflesh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-9439cb5e09cc44caa63dfbfb299df45f
Title: Retro computer
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/computer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      
      <mesh geometry={nodes.Object_2.geometry} material={materials.None} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/computer-transformed.glb')
